"""Add deposit_transferred field to enrollment table

Revision ID: 7e71ef0d0ef7
Revises: 901eba6f362d
Create Date: 2025-12-21 23:26:42.637884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e71ef0d0ef7'
down_revision = '901eba6f362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_transferred', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('deposit_transferred')

    # ### end Alembic commands ###