"""Add image fields to activity table

Revision ID: 901eba6f362d
Revises: 19d6847cc992
Create Date: 2025-12-21 23:18:24.869093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '901eba6f362d'
down_revision = '19d6847cc992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('images')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###